import type { Metadata } from "next";
import { Noto_Sans } from 'next/font/google'
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const notoSans = Noto_Sans({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <ReduxProvider> 
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
