import { ThemeProvider } from "@/providers/ThemeProvider";
import type { Metadata } from "next";
import './global.css'
import Wrapper from "@/containers/Wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Wrapper>
            {children}
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}

